### ISSUE TITLE
monocular depth task in mmlab

### ISSUE THREAD

**Issue by nonononentity** [zhyever/Monocular-Depth-Estimation-Toolbox#11]
Thank you for your code.
I did not find any repos corresponding to monocular depth task under mmLab project. Did you modify the "depth" based on MMCV framework by yourself, including metric, inference and so on.

I am now trying to make changes based on the MMsegmentation to fit mono.

**Comment by zhyever** [comment]
Yes, I modify the depth based on mmsegmentation by myself. The `/depth` folder is like `/mmsegmentation` in mmsegmentation project.

**Comment by zhyever** [comment]
Closs for now.
