### ISSUE TITLE
How to visualize validation images on tensorboard?

### ISSUE THREAD

**Issue by aj96** [zhyever/Monocular-Depth-Estimation-Toolbox#16]
in your tensorboard_hook.py, you have this line

"log_images = runner.outputs.get('log_imgs')" 

But this seems to only give the images from training set.

**Comment by zhyever** [comment]
Currently, our codebase can only log images during the training stage. If you'd like to extend the codes to support log images during the validation stage, you should do some hacks in the `tensorboard_hook.py`. While I have no plan to add this support, you can make a pr to share your implementation!

**Comment by aj96** [comment]
Thatis the thing. I do not see how to get validation images from tensorboard_hook.py? It always returns the training images regardless if it is validation phase or training phase.

**Comment by zhyever** [comment]
Yes, note that we only add images to loggers when training. Here is what we do now:

> First, see [this line of codes](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/2c054b40461b64c60ff7d1a4d7f4f0833e716eb7/depth/models/decode_heads/decode_head.py#L134), we add log images to depth_head's `losses` for a temporal save. 
> 
> Then, see [this line of codes](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/2c054b40461b64c60ff7d1a4d7f4f0833e716eb7/depth/models/depther/base.py#L113), we conduct a post-process of these loss terms mixed up with real losses and log images, dividing them into loss terms and images, respectively.
> 
> Finally, log images are saved as a key-value pair in training output as shown in [this line of codes](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/2c054b40461b64c60ff7d1a4d7f4f0833e716eb7/depth/models/depther/base.py#L152)
> 
> Hence, in `tensorboard_hook` [this line of codes](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/2c054b40461b64c60ff7d1a4d7f4f0833e716eb7/depth/models/utils/hooks/tensorboard_hook.py#L49), after ensuring this is the training stage, we can get the log images from the `runner.outputs.get('log_imgs')`.

For your case, if you wanna visualize images during validation, you need to do some hacks in `eval_hooks.py`. Remember the validation is achieved via hooks (This is a feature of MMcodebase). See [this line of codes](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/2c054b40461b64c60ff7d1a4d7f4f0833e716eb7/depth/core/evaluation/eval_hooks.py#L45), your logging process is achieved here. So you need to consider how to pass the log images to this function, where you can imitate our solutions for training stage logging.

**Comment by zhyever** [comment]
Close this issue for now.
