### ISSUE TITLE
For the configuration of the SUNRGBD dataset parameters?

### ISSUE THREAD

**Issue by hgj15189826157** [zhyever/Monocular-Depth-Estimation-Toolbox#17]
1.The model can predict the maximum and minimum depth values of the image, max_depth, min_depth?
2.During the evaluation phase, the maximum and minimum depth masks for the SUNRGBD dataset，max_depth_eval and min_depth_eval?
3.When using the depth map of the SUNRGBD dataset, do you choose the original depth map (which is missing), or the depth map in the depth_bfx folder that has already filled in the missing depth values?
4.Thanks to the author for answering this question, because many papers and codes do not mention any information.

**Comment by zhyever** [comment]
1. As far as I see, most models cannot predict max/min depth of images. Few methods propose to dynamically predict them for some purposes but are not included in this toolbox right now.
2. When evaluation, we only consider gt depth in a certain range, i.e., 0-10m for NYU. So, the max_depth_eval and min_depth_eval are used to filter invalid depth points in the evaluation.
3. I download the standard SUNRGBD and use their split to get train/val set. See the split filename, for example `
SUNRGBD/kv2/kinect2data/000002_2014-05-26_14-23-37_260595134347_rgbf000103-resize/depth/0000103.png`, there is no `depth_bfx`. Hence, I did not use the fixed depth. (ps: the transferred models are trained on NYU, where depth maps are  not filled, so it is reasonable to use unfilled depth maps.)

Thanks for your attention to our work. I hope these replies are helpful for you.

**Comment by zhyever** [comment]
Close for now.
