### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by kingoo123** [zhyever/Monocular-Depth-Estimation-Toolbox#18]
Dear author:
      I ran into this issue while testing on my own dataset. And hope to get your help.My configuration is as follows：
      The model is [depthformer_swinl_22k_nyu.pth](https://drive.google.com/file/d/1GMEgiiE-bkHYYD2xL8W6Qz50qa_P4T6e/view?usp=sharing) and config is  [depthformer_swinl_22k_w7_nyu.py](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/configs/depthformer/depthformer_swinl_22k_w7_nyu.py). In addition，I set sampler to:samples_per_gpu=1
,workers_per_gpu=1. How can I configure it to reduce cuda memory during testing?

**Comment by kingoo123** [comment]
And I would like to know how to test large scale images？Thanks

**Comment by zhyever** [comment]
The best solution is to change to a GPU with more memory. Since you have set `samples_per_gpu=1`, the `batch_size` is the minimum for the model inference on GPU. While I do not have much knowledge on saving memory, I wonder if you can run the model on CPU as introductions in our [inference](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/docs/inference.md) as

```
CUDA_VISIBLE_DEVICES=-1 python tools/test.py configs/depthformer/depthformer_swinl_22k_w7_nyu.py path/to/your/model --eval x
```

Testing large-scale images needs more consideration of model size. That's tough for our depthformer w/ swinL. Your can look for more light-weight methods, like the recent paper [SideRT: A Real-time Pure Transformer Architecture for Single Image Depth
Estimation](https://arxiv.org/pdf/2204.13892.pdf).

**Comment by kingoo123** [comment]
> 最好的解决方案是更换为具有更多内存的 GPU。由于您已设置`samples_per_gpu=1`，因此`batch_size`是 GPU 上模型推理的最小值。虽然我对节省内存知之甚少，但我想知道您是否可以在 CPU 上运行模型作为我们[推理](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/docs/inference.md)中的介绍
> 
> ```
> CUDA_VISIBLE_DEVICES=-1 python tools/test.py configs/depthformer/depthformer_swinl_22k_w7_nyu.py path/to/your/model --eval x
> ```
> 
> 测试大规模图像需要更多考虑模型大小。这对我们的带 swinL 的 depthformer 来说很难。您可以寻找更轻量级的方法，例如最近的论文[SideRT: A Real-time Pure Transformer Architecture for Single Image Depth Estimation](https://arxiv.org/pdf/2204.13892.pdf)。

Thank you very much for your reply.

> The best solution is to change to a GPU with more memory. Since you have set `samples_per_gpu=1`, the `batch_size` is the minimum for the model inference on GPU. While I do not have much knowledge on saving memory, I wonder if you can run the model on CPU as introductions in our [inference](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/docs/inference.md) as
> 
> ```
> CUDA_VISIBLE_DEVICES=-1 python tools/test.py configs/depthformer/depthformer_swinl_22k_w7_nyu.py path/to/your/model --eval x
> ```
> 
> Testing large-scale images needs more consideration of model size. That's tough for our depthformer w/ swinL. Your can look for more light-weight methods, like the recent paper [SideRT: A Real-time Pure Transformer Architecture for Single Image Depth Estimation](https://arxiv.org/pdf/2204.13892.pdf).

Thank you very much for your reply. I have tested on 3090 and I'm afraid it won't work on cpu because I have a lot of pictures. Now my solution is to crop the original image.

**Comment by zhyever** [comment]
OK! That will be interesting to explore how to infer from high-resolution images effectively. Close this issue for now, but feel free for more discussions!
