### ISSUE TITLE
Binsformer

### ISSUE THREAD

**Issue by roymiles** [zhyever/Monocular-Depth-Estimation-Toolbox#19]
Hi, 
thanks for working on this toolbox!
I was wondering if binsformer will be added any time soon?

**Comment by zhyever** [comment]
Thanks for your attention to our work. Currently busy with other things, I will release that parts of the codes by the end of May.

**Comment by zhyever** [comment]
:D Since the review results are not good enough, we decide to delay the release of codes.

**Comment by althafnazar7** [comment]
Hi,
Are there any updates on when the Binsformer code will be released?

**Comment by zhyever** [comment]
Updated. Have a check now.
