### ISSUE TITLE
About the Batch Size

### ISSUE THREAD

**Issue by BingyuanW** [zhyever/Monocular-Depth-Estimation-Toolbox#2]
Thanks for your great work!

In your paper, I find the batch size is set to 2. I want to konw  if a larger batch size can help improve the performance.

**Comment by zhyever** [comment]
Definitely possible. 

The key is that I use bs=8 in the experiment on a node with 2 3090s (see the config for swint) and bs=2 with 8 V100s (see the config for swinl). Hence, the total bs for Swint and Swinl are the same. Moreover, make sure your memory is enough since the swinl is such a large model.

When I reproduce our work based on this toolbox, I simply get better results than that provided in our paper. See the logs (will soon be provided) to get more details. Trained models will also be released soon!

**Comment by BingyuanW** [comment]
> Definitely possible.
> 
> The key is that I use bs=8 in the experiment on a node with 2 3090s (see the config for swint) and bs=2 with 8 V100s (see the config for swinl). Hence, the total bs for Swint and Swinl are the same. Moreover, make sure your memory is enough since the swinl is such a large model.
> 
> When I reproduce our work based on this toolbox, I simply get better results than that provided in our paper. See the logs (will soon be provided) to get more details. Trained models will also be released soon!

So, the bs actually means "bs per GPU" ? Generally, I train my network with DataParallel,  and I am not quite familiar with DistributedDataParallel.

**Comment by zhyever** [comment]
> > Definitely possible.
> > The key is that I use bs=8 in the experiment on a node with 2 3090s (see the config for swint) and bs=2 with 8 V100s (see the config for swinl). Hence, the total bs for Swint and Swinl are the same. Moreover, make sure your memory is enough since the swinl is such a large model.
> > When I reproduce our work based on this toolbox, I simply get better results than that provided in our paper. See the logs (will soon be provided) to get more details. Trained models will also be released soon!
> 
> So, the bs actually means "bs per GPU" ? Generally, I train my network with DataParallel, and I am not quite familiar with DistributedDataParallel.

Yes, DDP is used as default and bs means "bs per GPU", as shown in the config:
https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/4bd7d0932f1daaba6cc8016a8b3402806c833ec2/configs/depthformer/depthformer_swinl_22k_w7_nyu.py#L32

I recommend using DDP for better effectiveness during training.

**Comment by BingyuanW** [comment]
> > > Definitely possible.
> > > The key is that I use bs=8 in the experiment on a node with 2 3090s (see the config for swint) and bs=2 with 8 V100s (see the config for swinl). Hence, the total bs for Swint and Swinl are the same. Moreover, make sure your memory is enough since the swinl is such a large model.
> > > When I reproduce our work based on this toolbox, I simply get better results than that provided in our paper. See the logs (will soon be provided) to get more details. Trained models will also be released soon!
> > 
> > 
> > So, the bs actually means "bs per GPU" ? Generally, I train my network with DataParallel, and I am not quite familiar with DistributedDataParallel.
> 
> Yes, DDP is used as default and bs means "bs per GPU", as shown in the config:
> 
> https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/4bd7d0932f1daaba6cc8016a8b3402806c833ec2/configs/depthformer/depthformer_swinl_22k_w7_nyu.py#L32
> 
> I recommend using DDP for better effectiveness during training.

Understand ！I use DP because I find DDP often leads to unknown errors.  My hardware is a computer with 4 GPUs, DP is more convenient for me to debug :)

**Comment by zhyever** [comment]
That is the key reason why I start this project built on mmseg. There is no difficulty in using DDP anymore.

**Comment by BingyuanW** [comment]
OK, thanks for your reply. Closing the issue for now.
