### ISSUE TITLE
How to use mixed-precision training?

### ISSUE THREAD

**Issue by Len-Li** [zhyever/Monocular-Depth-Estimation-Toolbox#22]
Hi, thanks for sharing your work!
I want to save GPU memory during training. I follow this [link](https://zhuanlan.zhihu.com/p/375224982) to set up FP16 setting. I simply add `fp16 = dict(loss_scale='dynamic') ` in the bottom of confi. However, the memory doesn't change. Do you have any advice on it?

**Comment by zhyever** [comment]
Unfortunately, I did not consider the FP16 training when I implemented this repo, so the interfaces in codes are not accomplished now. But I think you can follow the docs to add the decorated `@auto_fp16` to the forward functions.

**Comment by zhyever** [comment]
Close this issue for now
