### ISSUE TITLE
enexpected key & missing keys occur  when loading dpt model

### ISSUE THREAD

**Issue by gaolizhao** [zhyever/Monocular-Depth-Estimation-Toolbox#23]
use the following commands for infer:

 python tools/test.py configs/depthformer/dpt_vit-b16_nyu.py \
    checkpoints/dpt_vitb_nyu_50e.pth \
    --eval x
where dpt_vitb_nyu_50e.pth is offered by the author.

The following happened and result is wrong.
<img width="851" alt="image" src="https://user-images.githubusercontent.com/24197388/170456494-7b14281d-ecd6-4259-a8e5-9773f025deea.png">

**Comment by zhyever** [comment]
Maybe I upload the wrong model to google drive. I will have a check.

**Comment by zhyever** [comment]
Download the model again, utilize the latest version of the codebase, and have a try again. Close this issue for now.
