### ISSUE TITLE
Depth Prediction and  Depth Completion

### ISSUE THREAD

**Issue by HelloWorld4096** [zhyever/Monocular-Depth-Estimation-Toolbox#25]
Helo! I'm a little confused now. I don't know the difference between depth completion and depth prediction. The main difference I see on kitti is that depth prediction is basically monocular completion, and depth completion is color image, depth image and true value depth. I am currently studying depth completion, but due to insufficient computing power (2080ti * 2, about 16 days), I would like to know how long the depth prediction training time will be. Hope to get your reply.

**Comment by zhyever** [comment]
Thanks for your attention to our work.

While I have not conducted research projects about depth completion, I will share some of my understanding and hope they are helpful for your research. 

As for depth estimation, the model receives the input RGB images and outputs corresponding *full depth estimation maps* (full means there are values at each image location). However, in terms of depth completion, the model can get input RGB images and also *sparse depth maps* (sparse means there are missed depth values in depth maps). The output is the full depth estimation map, similar to the depth estimation task.

As for the computing resource, I think that correlates with your selected models, methods, and, of course, training epochs, etc. I have not tested our implemented methods on 2080ti * 2, but several experiments are conducted on 3090 * 2. For example, it takes about 5 hours to train the [BTS](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/tree/main/configs/bts). It can be a reference to estimate the real training time on your machine.

**Comment by HelloWorld4096** [comment]
Thank you very much for your reply, it helped me a lot

**Comment by zhyever** [comment]
Good luck! Close this issue for now.
