### ISSUE TITLE
Ask for Quickly Inference

### ISSUE THREAD

**Issue by tp655998** [zhyever/Monocular-Depth-Estimation-Toolbox#26]
Is there any method to use trained models inference any images without other setting?

**Comment by zhyever** [comment]
See our [instruction](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/docs/inference.md). You can download any pre-trained models provided in the [model_zoo.md](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/docs/model_zoo.md), and achieve quick inference.

**Comment by tp655998** [comment]
Sorry, I know how to inference test data by the above command,
but i mean that I hope to test images without groundtruth and focal and create data list(such as nyu_test.txt)...

**Comment by zhyever** [comment]
All right, I got what you mean. Actually, all these functions are supported by my toolbox. Right now, I am sort of busy making detailed instructions for users, but I still would like to try my best to help you. :D Here are some simple introductions and I holp they will be helpful for your work. 

(1) I suppose that you have a new (custom) dataset. There is no gt, focal, or data list. First, you can easily organize your dataset as:

── custom_dataset
│   ── rgb
│  │   ── 0.xxx
│  │   ── 1.xxx

(2) Create a new config for your custom dataset. Notice to set the `test_mode=False` for the data config. As a result, the dataset will not try to load any gt images. Other settings like the model can be simply adopted from other configs.
```
train=dict(
    type='CustomDepthDataset', # use the custom dataset
    pipeline=dict(...), # simple pipeline
    data_root='data/custom_dataset', # path to your datset
    test_mode=True, # it is important to set test_model=True, hence only images will be loaded (from nfs/custom_dataset/rgb).
    min_depth=1e-3, # custom
    max_depth=10, # custom
    depth_scale=1) # custom
```

(3) To get inference predictions, just follow the second tip in [Inference](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/docs/inference.md). The toolbox will save predicted depth maps into the specific folder.

PS: I recommend seeing the [custom dataset class](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/depth/datasets/custom.py) for details. I think basic requirements can be achieved by several simple modifications. Thanks for your attention to my work. 😃
