### ISSUE TITLE
Training model on Custom Dataset

### ISSUE THREAD

**Issue by EkjotSingh898** [zhyever/Monocular-Depth-Estimation-Toolbox#28]
Hi, thank you for your amazing work. Can you please share with us about how to train a model like- depthformer on Custom dataset.

**Comment by zhyever** [comment]
Some instructions can be seen [here](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/docs/dataset_prepare.md#custom-dataset). Other discussions about the custom dataset can be referred to #26.

Now, I'm conducting a novel project (MAI challenge) using this toolbox, utilizing a custom dataset. After it ends, I will release the related codes and models. Please keep attention to this toolbox, I will progressively add more development details and examples.
