### ISSUE TITLE
About KITTI 

### ISSUE THREAD

**Issue by djx99** [zhyever/Monocular-Depth-Estimation-Toolbox#3]
Thanks for your work
For the KITTI dataset, did you fill the GT depth map during the training process, and what filling method did you use? And what is the meaning of the eval-mask in your code?

**Comment by zhyever** [comment]
Thanks for your attention.

For the KITTI dataset, we use sparse GT depth maps during training, where invalid depth values are filtered through masks (gt_depth > 0). If you wanna fill in GT depth maps, I recommend referring https://github.com/ialhashim/DenseDepth.

As for eval-masks which are used in not only KITTI but also NYU, SUN-RGBD, *etc*, we follow previous work to evaluate estimation results of a certain area in images. I guess perhaps there are slight errors in the fringe of GT. Take an instance of the KITTI dataset, the grag_crop is a crop according to Garg  ECCV16, and the eigen_crop is a crop according to Eigen NIPS14, respectively. 

See https://github.com/mrharicot/monodepth/blob/b76bee4bd12610b482163871b7ff93e931cb5331/utils/evaluate_kitti.py#L12.

**Comment by djx99** [comment]
Thanks for the answer：）
