### ISSUE TITLE
Question about the scene query generation in BinsFormer method?

### ISSUE THREAD

**Issue by rockywind** [zhyever/Monocular-Depth-Estimation-Toolbox#31]
Hi,
Thank you for your excellent work.
I have two question.
1. How to generate the scene classification label?
2. How to generate the scene query?

**Comment by zhyever** [comment]
Thanks a lot for your attention to our work. Here are my replies to your answers.

1. Generally, depth estimation datasets are organized by scene names. So for NYU depth, I classify scenes into about 19 classes, including bedroom, classroom, and so on.
2. That's easy to access, thanks to the extensibility of the attention mechanism. We add an extra query to the bins queries. So, as presented in the figures of our paper, the query set consists of a scene query and N bins queries.

**Comment by rockywind** [comment]
Thank you for your reply!
1. Don't we need scene query and scene classification loss in the KITTI dataset?
2. Why are there no background Bin in the Binsformer method? There is a ground Bin in the CaDDN method.

**Comment by zhyever** [comment]
1. I think we do not need and I did not implement scene query and cls loss for the KITTI dataset. But if there are reasonable classifications for such outdoor street datasets, it can be useful to add the classification part.

2. That's an interesting question. I list my understanding below.

First, let's see the depth estimation. Remember our goal is to predict pixel-wise depth, it is not necessary to divide pixels into fore- and background classes. (While there are several works indicating that a separated manner can benefit the depth estimation, it is hard to get accurate and fine-grained labels for this goal especially when we adopt LIDAR gt). 

Now, let's consider Mono3D, more specifically, the CaDDN. The depth estimation is used to lift up the image features into space frustum (i.e., voxel). If we use regressithe on-based method here, the result features are too discriminative, leading to error cascade and performance degradation (proofed in their ablations). When adopting cls.-based method, the features are more smooth (imagining that the probability cannot be one-hot). And, here, is the point. Consider a pixel belonging to the background, and if we use the background bins, the lifted features are near zero (remember the dot operation). That's similar to the voxel-based point cloud 3D detectors (empty voxels). But if there is no background bin, the probability distribution can be close to the max depth, introducing futile noises and decreasing the detection performance (especially severe for distant objects).

**Comment by zhyever** [comment]
Close for now.
