### ISSUE TITLE
Convert to ONNX model

### ISSUE THREAD

**Issue by Lilyo** [zhyever/Monocular-Depth-Estimation-Toolbox#35]
Hi @zhyever, 
Thanks for your great work! I'm curious if BinsFormer can be converted to ONNX model? If yes, please also provide sample code so we can verify it.

Thanks in advance!

**Comment by zhyever** [comment]
I have implemented several codes to convert the model to ONNX but not release in this repo now. The most tricky issue is whether the ONNX has supported ops in models.

Relative codes can be like:

```
    sample_input = torch.randn(1, 3, 480, 640)
    input_nodes = ['input']
    output_nodes = ['output']
    
    print("\n\n\n Start export onnx")
    # torch.onnx.export(model, sample_input, "model.onnx", export_params=True, input_names=input_nodes, output_names=output_nodes)
    torch.onnx.export(model, sample_input, "nfs/model.onnx", export_params=True, input_names=input_nodes, output_names=output_nodes, opset_version=11)

    # Converting model to Tensorflow
    print("\n\n\n Start export_graph")
    onnx_model = onnx.load("nfs/model.onnx")
```

**Comment by Lilyo** [comment]
Hi @ReBoRn8888 , 
I guess that you must pass 'img_metas' when feeding forward based on current coding style sin. A possible solution is that:
1. Generating dummy 'img_metas', then
2) decoupling 'img_metas' and 'img' when you feed into onnx feed forward(doing so, your input won't be dict anymore).

**Comment by zhyever** [comment]
Sorry for the late reply, I missed your questions. Yes, the input of the model during converting should be single. In other words, the forward function should be like: `def forward(self, x)`. No more parameters are supported. Before you convert the model, you should hack a `def forward(self, x)` in the depther, so that the converter can successfully pass variables.

**Comment by zhyever** [comment]
Close for now.

**Comment by a227799770055** [comment]
@ReBoRn8888  Hi, I am also trying to convert the model to ONNX. However, I encounter the error like below. Do you have any experiences to deal with that?
![image](https://user-images.githubusercontent.com/50135574/202972411-237eecd7-497c-4d85-9bc8-830f49a0e734.png)
