### ISSUE TITLE
Preparation NYUdepthv2

### ISSUE THREAD

**Issue by seb-le** [zhyever/Monocular-Depth-Estimation-Toolbox#36]
Hi. First of all, thank you for sharing your nice work.

I faced an issue when I organize the nyudepthv2 dataset.

As described in [dataset_prepare.md](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/docs/dataset_prepare.md#prepare-datasets), I tried to run follows:
```shell
$ git clone https://github.com/cleinc/bts.git
$ cd bts
$ python utils/download_from_gdrive.py 1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP sync.zip
$ unzip sync.zip
```

Next, what file should I download in [link](https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html) to get the standard test set that you mentioned? 

![image](https://user-images.githubusercontent.com/74757131/178991549-27726980-3dc0-43a9-963e-48212d134f8f.png)

Also, where can I get nyu_train.txt and nyu_test.txt?

Thanks.

**Comment by seb-le** [comment]
Thank you for your reply, and I found the splits txt files.

However, I think It is not included in sync.zip; instead, it is included in [link](https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html) and extracted by the BTS source code as follows:
```shell
$ cd ~/workspace/bts/utils
### Get official NYU Depth V2 split file
$ wget http://horatio.cs.nyu.edu/mit/silberman/nyu_depth_v2/nyu_depth_v2_labeled.mat
### Convert mat file to image files
$ python extract_official_train_test_set_from_mat.py nyu_depth_v2_labeled.mat splits.mat ../../dataset/nyu_depth_v2/official_splits/
```
Then, we might cut the test set and paste it into our dataset structure.

On the other hand, why the number of training pairs is 50k in the NYUdepthv2 dataset?

In nyu_train.txt, there are only 24,225 pairs for training.

**Comment by zhyever** [comment]
Thanks a lot for your report. That's a typo in the paper. We use this provided split file to train our models following previous work. I will zip my nyu dataset and upload it to drive in the future so that there will be no more effort to download or process the dataset using codes from other repos.

**Comment by seb-le** [comment]
Thank you for your comments.

I have really learned a lot of things from your work and paper.

Thanks.

**Comment by zhyever** [comment]
It's nice to hear that. I hope they are helpful to you. Feel free to re-open this issue for discussions.

**Comment by vuba-blog** [comment]
> It's nice to hear that. I hope they are helpful to you. Feel free to re-open this issue for discussions.

I am sorry, but is the test dataset available now?
