### ISSUE TITLE
 inference with kitti dataset

### ISSUE THREAD

**Issue by doshinle** [zhyever/Monocular-Depth-Estimation-Toolbox#41]
Excuse me, when I use the kitti dataset to test, the corresponding data cannot be loaded, and the splits file cannot be loaded even if I try to modify it.

[                                                  ] 0/696, elapsed: 0s, ETA:Code/Monocular-Depth-Estimation-Toolbox-main/Monocular-Depth-Estimation-Toolbox-main/depth/ops/wrappers.py:23: UserWarning: When align_corners=True, the output would more aligned if input size (176, 608) is `x+1` and out size (352, 1216) is `nx+1`

**Comment by zhyever** [comment]
Please provide the full error info so that I can help to check. This warning can be simply neglected.

**Comment by doshinle** [comment]
> 请提供完整的错误信息，以便我帮助检查。这个警告可以简单地忽略。

No error is reported, but the result of running is a solid color image.

**Comment by doshinle** [comment]
> Please provide the full error info so that I can help to check. This warning can be simply neglected.

No error is reported, but the result of running is a solid color image.

**Comment by zhyever** [comment]
Refer to Issue #34. There is a convergence issue.

**Comment by doshinle** [comment]
> Refer to Issue #34. There is a convergence issue.

Thank you for your reply.
