### ISSUE TITLE
BinsFormer - model size mismatch

### ISSUE THREAD

**Issue by robertsulej** [zhyever/Monocular-Depth-Estimation-Toolbox#42]
Hi,

I'd like to test various models performance on my images before diving into details of particular model. Your toolkit looks perfect for such comparison. I managed to run DepthFormer on my custom dataset, but have an issue with BinsFormer.

Model binsformer_swinl_nyu_converted loads and the code runs, but it complains about loaded shapes:

```
The model and loaded state dict do not match exactly

size mismatch for decode_head.conv_depth.weight: copying a param with shape torch.Size([1, 96, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 256, 3, 3]).
```

I've tried to fix it by myself but got lost in the code. Could you help, please?

**Comment by zhyever** [comment]
You can neglect this warning. 

As the model's name, this checkpoint is a converted version. `conv_depth` is actually not used in BinsFormer. There are some redundant codes in this version since I'm not ready to prepare machines to reproduce our experiments.

Just waiting for the evaluation script. You will see the correct results (NYU):
```
The model and loaded state dict do not match exactly

size mismatch for decode_head.conv_depth.weight: copying a param with shape torch.Size([1, 96, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 256, 3, 3]).
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 654/654, 11.4 task/s, elapsed: 57s, ETA:     0sSummary:

+--------+--------+--------+---------+--------+--------+----------+--------+--------+
|   a1   |   a2   |   a3   | abs_rel |  rmse  | log_10 | rmse_log | silog  | sq_rel |
+--------+--------+--------+---------+--------+--------+----------+--------+--------+
| 0.9248 | 0.9894 | 0.9973 |  0.0935 | 0.3297 | 0.0395 |  0.1176  | 9.3452 | 0.0471 |
+--------+--------+--------+---------+--------+--------+----------+--------+--------+
'''

**Comment by robertsulej** [comment]
OK, thanks for clarifications!
