### ISSUE TITLE
handling of incomplete depth maps

### ISSUE THREAD

**Issue by mylifeasazucchini** [zhyever/Monocular-Depth-Estimation-Toolbox#43]
Hi! So I noticed that some images in the GT depth map are incomplete (or marked as 0 for those pixels) when there are reflective surfaces like glass, windows etc, how do you handle such pixels while calculating RMSE or other metrics ? Thx

**Comment by zhyever** [comment]
Following previous works, pixels at these places are masked during evaluation. In other words, they do not take counts in evaluation.

**Comment by puyiwen** [comment]
> 在之前的工作之后，这些位置的像素在评估期间被屏蔽。换句话说，他们不计入评估。

Hi,do you mean the invalid depth do not participate in training and evaluation?
