### ISSUE TITLE
How can I download the test data on kitti benchmark

### ISSUE THREAD

**Issue by RuijieZhu94** [zhyever/Monocular-Depth-Estimation-Toolbox#44]
Thank you for providing the code framework in depth estimation.
The camera parameter in data/kitti/benchmark_test_cam can be downloaded in readme.md. But I cannot find the corresponding image data. Is it in kitti raw data?

**Comment by zhyever** [comment]
The kitti benchmark image data should be downloaded from their official website: [Download manually selected validation and test data sets (2 GB)](https://s3.eu-central-1.amazonaws.com/avg-kitti/data_depth_selection.zip).

**Comment by RuijieZhu94** [comment]
Thanks. I see.

**Comment by zhyever** [comment]
Close this issue for now.

**Comment by RuijieZhu94** [comment]
I got an error when I run the test code on the kitti benchmark.
-> No such file or directory: 'data/kitti/benchmark_test.txt'.
Can u provide the benchmark_test.txt file?

**Comment by zhyever** [comment]
Sorry that I missed this file. See the new version of the toolbox. I have uploaded this benchmark_test.txt in our split folder (named kitti_benchmark_test.txt).
