### ISSUE TITLE
Depth range for Binsformer official KITTI dataset

### ISSUE THREAD

**Issue by ashutosh1807** [zhyever/Monocular-Depth-Estimation-Toolbox#45]
Hi,

For Garg crop evaluation is done till 80m. But for the official kitti split what max depth have you taken for training as it will affect the final metric since the bin centers have to be between min and max depth. If possible can you release the training and evaluation (val) config for the official kitti online evaluation?

**Comment by zhyever** [comment]
Hi, sorry for the late reply. So busy these days. When adopting Eigen split, I use 0-80m following previous work to achieve a fair comparison. I remember I tried to extend the depth range from 0-80m to 0-88m when training for the benchmark, but the performance gain is slight.
