### ISSUE TITLE
Conceptual Questions about BinsFormer

### ISSUE THREAD

**Issue by onoyuki081** [zhyever/Monocular-Depth-Estimation-Toolbox#47]
Thanks for a great repo!
I have a question about BinsFormer architecture especially about 'auxiliary classification.'
From your code, I found that there are variables called class_num and n_bins. 
In my initial understanding from AdaBins is correct, I think AdaBins classifies the network output by n_bins, but it seems that BinsFormer's classification is done by class_num, where class here represents specific type of indoor scene (like bedroom, bathroom) in nyu.
But if so, why do we need such class in BinsFormer and how class contributes to 'auxiliary classification'?
If you need more clarification, I appreciate if you let me know.

**Comment by zhyever** [comment]
Close it for now.
