### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [zhyever/Monocular-Depth-Estimation-Toolbox#48]
Hi.

Thanks for the great repo!
Can you  please put a pretrained model for us to do inference on? It would be a Huge time saver. 

thanks in advance

**Comment by zhyever** [comment]
See config pages and refer to the model download links provided there. (Click the model name with hyperlinks in the READ.md)

**Comment by SuroshAhmadZobair** [comment]
Thank you!
