### ISSUE TITLE
Question about saving depth as uint16 type

### ISSUE THREAD

**Issue by ssh10032** [zhyever/Monocular-Depth-Estimation-Toolbox#49]
Hi, I'm trying to save Depth Estimation results(png) from my custom dataset.

I want to save the estimated results as **uint 16 type,** 
but it's saved as uint 8 type, so could you tell me **how to save it as uint 16 type?**

And thank you for providing your code.
It is very helpful for studying!

**Comment by zhyever** [comment]
Refer to [https://github.com/zhyever/LiteDepth/blob/958cf4ea12060e80eacf08a0f4077003db9d9d11/projects/toolbox_plugin/datasets/mobile_ai_2022_dataset.py#L21], where we first save the images with np.int16. (.npy)

Then, refer to [https://github.com/zhyever/LiteDepth/blob/958cf4ea12060e80eacf08a0f4077003db9d9d11/tools/convert_format.py#L31], where we actually load the result(.npy) again and use cv2 to save it as unit 16 type images.

**Comment by zhyever** [comment]
Close it for now.
