### ISSUE TITLE
About pre-trained model

### ISSUE THREAD

**Issue by DJInori** [zhyever/Monocular-Depth-Estimation-Toolbox#5]
Thanks for an excellent work!
In this paper, models not mention pre-trained are pre-trained by ImageNet-1K, right?
Do you try any other pre-trained model in exp?

**Comment by zhyever** [comment]
Hi, thanks a lot for your attention. 
In the DepthFormer paper, models without mentioning pre-training settings are trained by ImageNet-1K.
That is an extremely interesting issue actually. During experiments of SimIPU, I compare model performance based on different pre-trained models with different strategies, including Moco-v2, DenseCL, and so on. There is a discrepancy between them, which means that **"which pre-training strategy is suitable for monodepth"** is still an unresearched area. There should be more research and this toolbox provides a simple yet effective tool for evaluation, where you only need to change the pre-training model path in configs.

**Comment by DJInori** [comment]
Thanks for your reply!
