### ISSUE TITLE
Do such a large number of nyu datasets have semantic labels?

### ISSUE THREAD

**Issue by tb2-sy** [zhyever/Monocular-Depth-Estimation-Toolbox#51]
The standard nyu dataset contains not only depth information, but also semantic information. Does the nyu dataset used here have semantic information?

**Comment by zhyever** [comment]
Not yet. I have not conducted related projects. But I think you can extend our codes to support the requirement if needed.

**Comment by zhyever** [comment]
Close this issue for now.
