### ISSUE TITLE
Question for training scratch from custom dataset.

### ISSUE THREAD

**Issue by Albert-learner** [zhyever/Monocular-Depth-Estimation-Toolbox#53]
Hello, I'd like to train binsformer model to do Depth Prediction. I have some questions:

1. I'd like to train my custom dataset. What should I have to modify for training from scratch?
2. My custom dataset's image is one-channel image. So I have to train Swin-Transformer not using pretrained model. Which parts did I have to change?
3. My dataset Folder structure is like this:

```data  
    |-   custom  
              |-     train  
                        |-    A  
                                 |-       1  
                                            |-   ~~~~~.png  
                                            |-   ...  
                                            |-   ~~~~~.png  
                                 |-       ...  
                                 |-       2  
                        |-      ...  
                        |-     B  
              |-     val    
                       |-      C   
                                    |-     1  
                                             |- ~~~~~.png  
```
I'm trying to change your depth/dataset/custom.py file.

**Comment by zhyever** [comment]
1. You can refer to my new repo about LiteDepth. That's an example of using this toolbox and adopting a new dataset.
2. The simplest way in my view is to stack your one-dimension image into three dimensions before feeding it into the network.

**Comment by puyiwen** [comment]
> 

Hi,I want to know thow do you get the ground truth depth of your custom dataset? Use the RGB-D camera or using a pre-trained big model to inference the ground truth? Thank you very much!

**Comment by zhyever** [comment]
Actually, I just follow previous works, mainly adopting RGB-D camera or point cloud projections. I think a pre-trained big model can also be OK and you can also refer to some related papers about this.

**Comment by zhyever** [comment]
Close for now.
