### ISSUE TITLE
fine tune on custom dataset

### ISSUE THREAD

**Issue by Boraly** [zhyever/Monocular-Depth-Estimation-Toolbox#55]
Hello!

I would like to fine-tune the depthformer_swinl_22k_27 model on my custom dataset. I tried to follow the instruction but still have some issues. The main problems I have are:

1. How should a custom config for fine-tuning look like? I tried to copy an existing one and just change the dataset to my custom one, but that doesn't function properly.
2. How should the folder with the custom dataset be named? I was seeing different answers to this in some already solved issues and the instruction (either data/custom or data/custom_dataset)

I could share the custom files I used for my approach and the error message I got, if you want. 

Thank you in advance,
Boraly

**Comment by Chun-wei-Ho** [comment]
Hello Boraly,

I didn't see a straightforward way to do this. You may want to change the `__base__` variable in the [configuration](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/configs/depthformer/depthformer_swinl_22k_w7_kitti.py#L1-L4) . Edit [_base_/datasets/custom.py](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/configs/_base_/datasets/kitti.py) accordingly. Change the `train_pipeline` and `test_pipeline` in [_base_/datasets/custom.py](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/configs/_base_/datasets/kitti.py)  to the class name of your dataset (also remember to register it using `@DATASETS.register_module()`). Change the arguments in the `data` variable in [_base_/datasets/custom.py](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/configs/_base_/datasets/kitti.py) .

If everything is done properly, the code should work. Hope you can figure out what you are missing soon.

**Comment by Boraly** [comment]
Okay, I got much further now. But got a KeyError. I didn't change the functions that are causing the error. Do you have an idea what the problem might be?

![image](https://user-images.githubusercontent.com/40334899/190901938-baef9ef8-58f5-41b4-bd4d-d58587c72580.png)

**Comment by zhyever** [comment]
@Chun-wei-Ho Thanks a lot for your support. I think all the notifications of adopting a custom dataset contain in your answer.

@Boraly That's an error about incorrectly loading the GT maps. It seems the dataset did not successfully read your GT data. Please check the codes and ensure that you set the correct path.

I provide my codes in my [new paper repo](https://github.com/zhyever/LiteDepth), in which I conduct a more elegant installation of this toolbox and also include utilizing a custom dataset. See the [dataset](https://github.com/zhyever/LiteDepth/blob/main/projects/toolbox_plugin/datasets/mobile_ai_2022_dataset.py), this class inherits the custom_data and you can compare with yours.

**Comment by zhyever** [comment]
Close it for now. Feel free to re-open for further discussion.
