### ISSUE TITLE
Where are the kitti_eigen_train.txt and  kitti_eigen_test.txt?

### ISSUE THREAD

**Issue by chaytonmin** [zhyever/Monocular-Depth-Estimation-Toolbox#56]
Could you provide the kitti_eigen_train.txt and  kitti_eigen_test.txt, benchmark_train.txt, benchmark_test.txt?

**Comment by zhyever** [comment]
Check here: https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/tree/main/splits
I provide them in the `split` folder.

**Comment by chaytonmin** [comment]
> Check here: https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/tree/main/splits I provide them in the `split` folder.

Thanks！

**Comment by zhyever** [comment]
Hope it is helpful. Close this issue for now.
