### ISSUE TITLE
BinsFormer‘s config and model on Kitii

### ISSUE THREAD

**Issue by ciwei123** [zhyever/Monocular-Depth-Estimation-Toolbox#58]
@zhyever Thanks for your sharing. Could you share the BinsFormer‘s config and model on Kitii ? I want to train my model on Kitti, but I don't konw the config file. Thank you very much!!

**Comment by zhyever** [comment]
Work slowly these days. Soon will be done.

**Comment by zhyever** [comment]
I have updated the config. Check the new version. Close this issue for now.

**Comment by gcr** [comment]
hii! thanks for your hard work! is it possible to release the trained model for KITTI in addition to the config? (asking because we'd like to compare one of our models to a released binsformer checkpoint)
