### ISSUE TITLE
Make checkpoints available

### ISSUE THREAD

**Issue by stevebottos** [zhyever/Monocular-Depth-Estimation-Toolbox#6]
Hello, it looks like checkpoints are necessary in order to test these models - would it be possible to make checkpoints available soon? Thanks!

**Comment by zhyever** [comment]
Yes, I will provide all these models in the next version.

**Comment by kingoo123** [comment]
> Yes, I will provide all these models in the next version.

Hello,I wonder when the next version will be released? I can't wait to test it

**Comment by zhyever** [comment]
Well. In this current version, I provide a pre-trained depthformer model (see https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/tree/main/configs/depthformer), which can be used to familiarize this toolbox. 

Now, I'm uploading other models, which are kind of larger, to the google drive. I will finish it ASAP.

**Comment by zhyever** [comment]
All pre-trained models are available—close this issue for now.
