### ISSUE TITLE
Real depth or absolute depth.

### ISSUE THREAD

**Issue by ashank-art** [zhyever/Monocular-Depth-Estimation-Toolbox#60]
Hi, Thank you for the great work. Can I know the depth values obtained here are real depth values or absolute depth.?

**Comment by ashank-art** [comment]
Okay Thank you. Can you tell what is the procedure for evaluating the model on custom dataset?

**Comment by zhyever** [comment]
You can refer to related issues or refer to [LiteDepth](https://github.com/zhyever/LiteDepth), where I provide an implementation example for evaluating the custom dataset.
