### ISSUE TITLE
two questiones

### ISSUE THREAD

**Issue by ray-peng** [zhyever/Monocular-Depth-Estimation-Toolbox#65]
hi ! There are two questiones. 1, i can't find the pretrained checkpoint,  can you release it? 2. i just want to get the true depth map, so when i used the pretrained model to predict a img and got the predicted map, how to translate the predict value to true depth? thanks for your answer

**Comment by zhyever** [comment]
1. Just refer to the config page like [link](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/tree/main/configs/adabins). You can see the pre-trained ckps.
2. For supervised monodepth methods, the model prediction is exactly the true depth.

**Comment by zhyever** [comment]
Close this issue for now. Feel free to re-open it for further discussion.
