### ISSUE TITLE
Convert to ONNX error

### ISSUE THREAD

**Issue by a227799770055** [zhyever/Monocular-Depth-Estimation-Toolbox#68]
Hi @zhyever ,

Thank you for your great work. I have a problem about convert the model to ONNX.
When I convert model to ONNX, then I want to inference with onnxruntime.InferenceSession("model.onnx"), the error occur as below
`sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from test_neck.onnx failed:Node (ReduceSum_297) Op (ReduceSum) [ShapeInferenceError] axis must be in [-rank, rank-1]. input rank was 1` 

The error seems to occur at HAHIHeteroNeck. Have you ever met the error before?

**Comment by zhyever** [comment]
Unfortunately, there are so many OPs not supported during the conversion. I guess the deformable attention is not on the support list right now. While I have not tried to convert DepthFormer, I did do some work on other network architecture. You could refer to [LiteDepth](https://github.com/zhyever/LiteDepth), in which repo I provide more codes for model conversion. Hope it could help you.
