### ISSUE TITLE
Support for NeWCRFs

### ISSUE THREAD

**Issue by ldkong1205** [zhyever/Monocular-Depth-Estimation-Toolbox#74]
Hi @zhyever, thank you so much for maintaining this repository! It helps me a lot 😆 

I noticed in the model zoo that there is a folder for NeWCRFs. I wonder when will the support for this model be available. Thanks again!

**Comment by zhyever** [comment]
Nice to hear it. 😄  

You can now use the [config](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/main/configs/newcrfs/newcrfs_swinl_22k_w7_nyu.py) provided in the newcrf folder to try reproducing the method. With limited time and resources, I haven't done many experiments on it. I'm not sure that codes in this repo can perfectly achieve the performance reported in the original paper. I guess you can refer to the [official repo]( https://github.com/aliyun/NeWCRFs) for code details, from which I build the newcrf support in this repo.

**Comment by ldkong1205** [comment]
Hi @zhyever, thank you for your suggestion~

Do you have existing pretrained models? Could you kindly include them in the model zoo?

**Comment by zhyever** [comment]
Sorry. For now, I haven't trained the NeWCRFs carefully, so I cannot include one. I use codes in this repo to measure NeWCRFs model size and inference speed in a unified benchmark (for my papers).

**Comment by ldkong1205** [comment]
Got it. Thank you for your information!

Wish you a happy Chinese New Year 🎉

**Comment by zhyever** [comment]
> Got it. Thank you for your information!
> 
> Wish you a happy Chinese New Year 🎉

Thank you. Hope that they are useful for you. Have a happy Chinese New Year too!
