### ISSUE TITLE
Can't find implementation of show_result function

### ISSUE THREAD

**Issue by ankuPRK** [zhyever/Monocular-Depth-Estimation-Toolbox#78]
Hi, 

Thanks so much for making this opensource toolbox. Could you point me to the implementation of this function:

https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/7c0c89c8db07631fec1737f3087e4f1f540ccd53/depth/apis/test.py#L129

Thanks!

**Comment by zhyever** [comment]
Please refer to https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/7c0c89c8db07631fec1737f3087e4f1f540ccd53/depth/models/depther/base.py#L206

**Comment by ankuPRK** [comment]
thanks!
