### ISSUE TITLE
About NYUDepth dataset

### ISSUE THREAD

**Issue by zsy950116** [zhyever/Monocular-Depth-Estimation-Toolbox#8]
Thanks for your great work!
I notice that the 'depth_scale' of nyu dataset is 1000. It confuses me. I want to know why is scale factor is 1000. Looking forward to your reply.

**Comment by zhyever** [comment]
I think GT depth maps of NYU are saved as gt(m)*1000, so there should be a scale factor of 1000 to convert the saved values to a real unit. Same situations in KITTI and other datasets. I follow previous work in my codes.

More information can refer to https://github.com/cleinc/bts/blob/9f026177dc82712a308438297391a76e786f46e2/pytorch/bts_dataloader.py#L131

**Comment by zsy950116** [comment]
您好，您的邮件我已经接收。
