### ISSUE TITLE
Question about 'depth_scale' in sun rgb-d

### ISSUE THREAD

**Issue by Z-chocking** [zhyever/Monocular-Depth-Estimation-Toolbox#85]
Hello,thanks for your great work.I have a question on sun rgb-d dataset.I notice you set the `depth_scale` as 8000, could you tell me the reason ? Will be thankful for your answer.
![1683903055247](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/assets/92561600/b7ae0be0-1b0c-4bae-8ace-ee1820059a54)

**Comment by zhyever** [comment]
Just follow other implementations

**Comment by zhyever** [comment]
Close this issue for now
