### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv.runner'

### ISSUE THREAD

**Issue by firaterdem** [zhyever/Monocular-Depth-Estimation-Toolbox#90]
I am getting the following error in implementing the code for the custom dataset. I've already installed mmcv-full. How can I solve this problem?

`python tools/train.py configs/bts/bts_r50_nyu_24e.py`

Error message:

`Traceback (most recent call last):
  File "tools/train.py", line 10, in <module>
    from mmcv.runner import init_dist
ModuleNotFoundError: No module named 'mmcv.runner'`

**Comment by zhyever** [comment]
Hi, thanks for your interest to this toolbox. Please check the mmcv version you installed. Note that this repo is currently based on mmcv 1.x.x, instead of mmcv 2.x.x. I suppose that you install a 2.x version mmcv.

Hope it helps.

**Comment by firaterdem** [comment]
Hi. Installing mmcv-full 1.4.5 solved the problem. Thank you.

**Comment by anamce** [comment]
Hi can you please make sure which python version, pytorch and cuda version are you using
