### ISSUE TITLE
Do you have plans to continue updating this project?

### ISSUE THREAD

**Issue by md5xwl** [zhyever/Monocular-Depth-Estimation-Toolbox#95]
Do you have plans to continue updating this project?

**Comment by zhyever** [comment]
Thanks for your attention. Since I found that current sota works using more and more complex repo, it's really hard for me to follow them with limited time and resource. But I'd still like to develop my own repo based on this toolbox. Hopefully, I would publish something new. uha

**Comment by md5xwl** [comment]
I agree with you，"It more and more complex".
And thank you!
